#include<iostream>
#include<string>
#include"windows.h"
#include <stdlib.h>
using namespace std;
void nhapten() {
    string a = "Phung Thanh Do";
    string c = "Do Mixi";
    string e, f ;
    cout << "Hay nhap ten toc truong: " << endl;
    getline(cin, e);
    
    while (e != c && e != a) {
        cout << "ban nhap sai ten toc truong, hay nhap lai" << endl;
        getline(cin, e);
        }
    cout << "ten khac thi sao: " << endl;
    getline(cin, f);
    while (f != c && f != a) {
        cout << "ban nhap sai ten toc truong, hay nhap lai" << endl;
        getline(cin, f);
    }
    cout << "tuyet voi" << endl; Sleep(500);
}
void giadinh() {
    string g;
    string h;
    string k,l;
    cout << "hay cho biet ai dep trai nhat: " << endl;
    getline(cin, g);
    cout << "ai de thuong nhat: " << endl;
    getline(cin, h);
    cout << "ai xinh gai nhat: " << endl;
    getline(cin, l);
    cout << "ai quyen luc nhat: " << endl;
    getline(cin, k);
    cout << "ban dung la nguoi cua bo toc!" << endl;
}
void velogo() {
    system("Color 0A");
cout << "                                                                                                                                                     " << endl; Sleep(50);
cout << "                                                                                                                                                     " << endl; Sleep(50);
cout << "                                                                             :5Bs i                                                                   " << endl; Sleep(50);
cout << "                                                                  X       iMBBBr BG s                                                                 " << endl; Sleep(50);
cout << "                                                       i,        :B  2B,hBBBBB  BBs BB                                                                " << endl; Sleep(50);
cout << "                                                     ,BB    B,   BB BBBBBBBBBBBBBBB XBB    ::                                                         " << endl; Sleep(50);
cout << "                                                   rBB2  9  Bs  sBBBBBBBBBBBBBBBBBB :BBS rs Br  ,h                                                    " << endl; Sleep(50);
cout << "                                             :,  rBBB  sBB5BBB ,BBBBBBBBBBBBBBBBBBBBBBBB2sB rBM  SB   i,                                              " << endl; Sleep(50);
cout << "                                            M9 rBBBB9rBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB  9B  B9                                              " << endl; Sleep(50);
cout << "                                          iBh BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBr BBsBB  ,s                                          " << endl; Sleep(50);
cout << "                                         2BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG XB                                          " << endl; Sleep(50);
cout << "                                    B    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBsBB,                                         " << endl; Sleep(50);
cout << "                                   iBr2BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB   r2                                    " << endl; Sleep(50);
cout << "                                  ,BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB9  B:                                    " << endl; Sleep(50);
cout << "                                  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBiBBsB                                   " << endl; Sleep(50);
cout << "                                 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                   " << endl; Sleep(50);
cout << "                              M  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBs                                  " << endl; Sleep(50);
cout << "                             :BB:BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBs rr                               " << endl; Sleep(50);
cout << "                             rBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBM5B                                " << endl; Sleep(50);
cout << "                             MBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                " << endl; Sleep(50);
cout << "                             BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                " << endl; Sleep(50);
cout << "                          S  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                                " << endl; Sleep(50);
cout << "                          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB ,G                             " << endl; Sleep(50);
cout << "                          iBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXB,                             " << endl; Sleep(50);
cout << "                           BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB2                              " << endl; Sleep(50);
cout << "                           BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB                               " << endl; Sleep(50);
cout << "                        2B,hBBBBBBBBBBBBBBBBBBh, SBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMBBBMBBBBBBBBBBBBBBBBBBBBBBBBBBB  ,                             " << endl; Sleep(50);
cout << "                        rBBBBBBBBBBBBBBBBBBBG      ,sBBBMBBBBBBBBBBBBBBBBBBBBBBBBBBBs  ,   s,,, , :srr29BBBBBBBBBBBBBBBBs                             " << endl; Sleep(50);
cout << "                         BBBBBBBBBBBBBBBBBB,               s9BBBBBBBMBBBBBMGG99i  ,, :r:,,                  GBBBBBBBBBBBBB                            " << endl; Sleep(50);
cout << "                          BBBBBBBBBBBBBBBX                                        2BBBBBBBBBBMr              rBBBBBBBBB2BBB                           " << endl; Sleep(50);
cout << "                           BBBBBBBBBBBBB:                  ,sBBBBBBGs,         ,BBBBG, :GBBBBBBBG             2BBBBBBBB :BBr                          " << endl; Sleep(50);
cout << "                          BBBBBBBBBBBBB                  2BBBBBBBBBBBBBM,     9BBBs   2BBBBBBsrBBB,            hBBBBBBs, BBM                          " << endl; Sleep(50);
cout << "                        rBBBBBBBBBBBBB                 ,BBBBi      9BBBBBB   BBBM    sBBBBBBBB  BBB             9BBBBBB, BBh                          " << endl; Sleep(50);
cout << "                        BBB 5BBBBBBBB                 ,BBB,      MBBBBBBBBB BBBs     MBBBBBBBB2  BBB             iBBBBB MBB                           " << endl; Sleep(50);
cout << "                       BBB r,BBBBBBB                  BBB       sBBBBBBBBBBBBBs      ,BBBBBBBB   BBB              ,BBBBBBBr                           " << endl; Sleep(50);
cout << "                       BBB  BBBBBBB,                 ,BBG       2BBBBBBBBBBBBM         BBBBBM    BBB                BBBBS                             " << endl; Sleep(50);
cout << "                       :BBB  MBBBBG                  iBBs        BBBBBBB9rBBB                    BBB                 BBB                              " << endl; Sleep(50);
cout << "                        sBBBh:BBBB                    BBB         sBBBBr GBBB                   MBBr                 :BB2                             " << endl; Sleep(50);
cout << "                          hBBBBBBh                    9BB9              sBBB5                  5BBB                   BBB                             " << endl; Sleep(50);
cout << "                              BBB                      MBBB:          ,BBBBBB                 BBBB                    ,BB2                            " << endl; Sleep(50);
cout << "                              BBB                       rBBBBBGssss9BBBBB,:BBB,            ,9BBB2                      BBB                            " << endl; Sleep(50);
cout << "                             ,BBG                         iGBBBBBBBBBBM:   rBBBBMi,    ,rMBBBBM                        GBB                            " << endl; Sleep(50);
cout << "                             iBBs                              ,,:i          rBBBBBBBBBBBBBB:                          sBB,                           " << endl; Sleep(50);
cout << "                             iBBs                                                :ss222ri                              sBB:                           " << endl; Sleep(50);
cout << "                             iBBs                                                                                      sBB                            " << endl; Sleep(50);
cout << "                             ,BBM                                                                                      GBB                            " << endl; Sleep(50);
cout << "                              BBB                                                                                      BBB                            " << endl; Sleep(50);
cout << "                              BBB                                                                                     ,BB9                            " << endl; Sleep(50);
cout << "                              :BBG                                                                                    BBB                             " << endl; Sleep(50);
cout << "                               BBB                                                                                   ,BBM                             " << endl; Sleep(50);
cout << "                               :BBM                                                                         :        BBB                              " << endl; Sleep(50);
cout << "                                BBB:                BB,                                                    BBB9     BBB:                              " << endl; Sleep(50);
cout << "                                 BBB                ,BBi                                          r,       iBB:    BBBs                               " << endl; Sleep(50);
cout << "                                  BBB                ,BBr                                        SBB              BBBs                                " << endl; Sleep(50);
cout << "                                  ,BBB                 BBG                                      iBB              BBBr                                 " << endl; Sleep(50);
cout << "                                   :BBB                 BBBr                                   sBB             2BBB,                                  " << endl; Sleep(50);
cout << "                                    ,BBB:                :BBBs                                BBB            :BBBM                                    " << endl; Sleep(50);
cout << "                                      BBBG                 :BBBB:                          ,BBBs           ,BBBB,                                     " << endl; Sleep(50);
cout << "                                       2BBBr                  9BBBB2,                   ,9BBBh           :BBBBr                                       " << endl; Sleep(50);
cout << "                                         BBBBi                   sBBBBBBMsi,      :rXBBBBBB:           sBBBBr                                         " << endl; Sleep(50);
cout << "                                          ,BBBB2                     r9BBBBBBBBBBBBBBBGs            rBBBBB,                                           " << endl; Sleep(50);
cout << "                                            ,BBBBBi                           ,                  sBBBBBs                                              " << endl; Sleep(50);
cout << "                                               sBBBBBs                                      ,sBBBBBBr                                                 " << endl; Sleep(50);
cout << "                                                  sBBBBBB9r                            :2MBBBBBBX,                                                    " << endl; Sleep(50);
cout << "                                                     ,sBBBBBBBBBG2r::,,    ,,:is2GBBBBBBBBBBr,                                                        " << endl; Sleep(50);
cout << "                                                           :2MBBBBBBBBBBBBBBBBBBBBBBM2i,                                                              " << endl; Sleep(500);
cout << "                                             ,        ::           ,  :,,rss,                      ,         ,     ,   :rsr,                          " << endl; Sleep(50);
cout << "                                sMMBBBBsMBBBBB sMBBB29BB  SBBGsshGB    ,ssssX2  s2X9G9BM 2SGG9B9GMMGBrGMhBMhMMBsGM9B:sBM9X9BG                         " << endl; Sleep(50);
cout << "                                BBBBMGBBMBMBB9 BBBMBBBMBisBBMBBBBBB   BMsr:r:2BsBrrrr:hsMXssr:BsrriiBBrr,B9ir:BB:r,BM9irii::Br                        " << endl; Sleep(50);
cout << "                              sBGGGM9BGGGGGB,,BMGB2BGMGBBMMMXBGMB: ,Bsirr2ssGiBiissr:MrB,srrsB,srirB9,:sB:rr:Bh::9B::rrX2sM,                         " << endl; Sleep(50);
cout << "                               BMM9MGMB99GGGB 2BMMB 9BGGGMBB hGMMB  BriirGrsG,sM:i9sr:X92:i2s5X:rs:sBs:,BB,sr:Bsi:B:iirMirGsri                        " << endl; Sleep(50);
 cout << "                             iBMG9B9MG9M9GGB BGMBX ,BGGMMB  BGGBs B2iiiB2rs2sBrriM:s,BB:r:Mrsi2rr:XB,r,BX:ss:BirsX:r:BMssss9B                        " << endl; Sleep(50);
         cout << "                     BBGGMBhGhBMGGGGiBGGB   BGGGB  sBGMB  B,s:BB::riirr:9B:r:B9,rrB,r:B:s,MB,:sBiirrrsri9rr:GBi,rr,B5                        " << endl; Sleep(50);
cout << "                             rBGM9BM9G9BGGGG2sMMMB ,BMGGGBi MMMMB sM:isBhsBrisrri92ir:B:r,MB,:2B,s,BG:,MB,rrrrrrihiriBh2Bs:2B                         " << endl; Sleep(50);
cout << "                             BMMGM2MGGMB9GGGGGGGBi BMMGGGMG BMGBs sB:rrG2BS,s2rsi:isrs5ir:Bh:,BG,s,Msi,BB,:G9:rr:B,si229s,XB                          " << endl; Sleep(50);
cout << "                            GBMMM9sMMMS5MMM9BBGGBSBMMMBGMGBGBGMB,  Bririr::9B,r:MB:rrrrriXBr,rB2r52BrssBs:,BBirsXBM:r:i:sBB                           " << endl; Sleep(50);
cout << "                           sBBBBBr2BMBiBBBBBBBBBBBMBBG9BBBBBMBBB   iBGXXhMGB9GM9BBhGBBGM92BhsBXX2ssB99rBs9GBiBG9s sBMMGMGi                            " << endl; Sleep(50);
cout << "                           9Bssr: BBBB si:  MGssGGBBB ,BBs,BMSs,     rssr,  :,    ,       iss:         r2i,         ,,,                               " << endl; Sleep(50);
 cout << "                                 :,,                  :                                                                                                            "; Sleep(50);                                                                                                                                       
}
void vetoctruong() {
   
cout <<":,,,,,,,,,,,,,,.,.,.,.,.,.,.,.,...,...,.....,.,...,...,.,...........,.,...,.,.,.,.,.,...,...,.,.,.,.,.,.,,,,,.,.,,,.,,,,,,,,,,,,:,:,:,:,:::,:::::::., . . .. " << endl; Sleep(500);
cout << ", ,.,.,.,.,.,.,.,...,...,.,.,.,.......,.,...........,.........................................,.,.,...,.,...,...,.,.,.,,,.,.,,,,,,,,,,,,,,,,,,,,,,:,:." << endl; Sleep(50);
cout << ", ,,.,.........................................................................................................,.....,.,...,.,.,.,.,.,.,.,,,,,,,,,,,,." << endl; Sleep(50);
cout << ", ,.................................................................. ..............................................,...,.......,.,.,.,.....,.,.,.,,, " << endl; Sleep(50);
cout << ". ............................................ ............... ... ........................................................,.......,.,.,.,...,.,.,.,, " << endl; Sleep(50);
cout << ", ....................................... . . . .         . . ... ....... ........................................................,...........,.,.,., " << endl; Sleep(50);
cout << ". ...................................... ...                 . . ..... . . . ..... ......................................................,.,...,.,.,, " << endl; Sleep(50); system("Color 0B");
cout << ", ,.................................. ... .       ;1K5U1Jc:     . . . ... ..................................................................,.,.,.,., " << endl; Sleep(50);
cout << ". .................... ... . . ..... . .     .7BBBBBBBBBBBBBJ        . . ... ... ..... ..........................................................,.,, " << endl; Sleep(50);
cout << ", ..................... ....... ... .      .BBBBBQBEXMBMBBBBBQ        . . . . . ... ..... . . ....................................................... " << endl; Sleep(50);
cout << ". .................... . . . . ... .     ,1BBBQBDDRBQBBBBBBBQBRBBgZs     . ... ..... ..... ... ...................................................... " << endl; Sleep(50);
cout << ", ......... ............... . . ...    cBQBBBBM6XZBBBBBBBQBQBBBBBBBBB   . . . . ... ..... . . . ... . ..... . ......................................, " << endl; Sleep(50);
cout << ". ................ . . ... ... . .   :gBBBBBBMgMBBBBBBBBBBQBQBBBBBBBBB   . . . . ... . . . . ... ....... . .......................................... " << endl; Sleep(50);
cout << ". ......... . . ....... . . . . .   vBBBBBBQgEBBBBBBBBBBM6srL1gBBBBQBBg   . . . . . . . . ..... . ..... ... ........................................, " << endl; Sleep(50);
cout << ". .... . ... ... ... . . . ... .    BBBBBBGEZRBBBBBBBBBpr:,,..,JRBQBQBQJ   . . . . . . ....... ..... ........... ... ................................ " << endl; Sleep(50);
cout << ". ......... . ... . ... . . ...    BBBBBBQRQBBBBBQBQgL:,,.,,::::s6EGQQBB7     . . . . . . . ... . . . ....... ......................................, " << endl; Sleep(50);
cout << ". .................... . . ... .  rBBBBBMgBBBBBBBBR;    .,,::;:;;sXp6OMBB      . . . . . . . . . ... . . ... ....... ................................ " << endl; Sleep(50);
cout << ". ....... . . . ..... ..... . .   gQBBQgQBBQBBBR2:    . ..::;irr7r1UpgQBB.,1,   . . . . . . . . ... . . . . ......................... .............., " << endl; Sleep(50);
cout << ". .. ........... . . . . . . . .  .BBBBBQBBBGs,      ....,,;r7r7sL7LspRBQ6XBQ,   . . . . . . . . . . . ....... . . .................................. " << endl; Sleep(50);
cout << ". ....... ... . ....... . . . .     DBBBBKJ:.   ..,.,.,,::;;r;i;7r7Lss6QBGROH5    . . . . . . . . . . . . ... . ... ................................. " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . . . . . .   BQBs,.......,,:,:::::,:,,.;;;;7cL1KDDQBOL7  . . . . . . . . . . . . . . ... ..... ... ... ... .................. " << endl; Sleep(50);
cout << ". ... ... . ... . . . . . . ... .    rBQL..,:,:,,,:,:::,,.   :UMgPHSSsJLJXGBP;2.  . . . ... . . . . . . . . . . . . . . ... . ..... ................. " << endl; Sleep(50);
cout << ". .. ... . ... ... . . . . . . . .    BBSr,::;::::,,.,,,...;6BBPsXOQgPJsLs1Z5;L,   . . . . . . . . . . . . . . . . ... . . . ... . . ..... .......... " << endl; Sleep(50);
cout << ". ......... ... . . . . . . . . . .   :B6Ur;;;;::..  .:,,:LRBGGGBBBMacriL2SPXr1   . . . . . . . . . . . . . . ... . . . ................. ....... ... " << endl; Sleep(50);
cout << ". .... . ... . . . . . . . . . . . .   5BGLri;:,   .,:::;sZBRBBiEQZE;::;LHaKGw.  . . . . . . . . . . . . . . . . . ... . . . . ... ... . . .......... " << endl; Sleep(50);
cout << ". ... ....... . . . . . . . . . . . .   HBa:i:,,;JOEHs2JvLZRg6L;vUp; .:7UP66J     . . . . . . . . . . . . . . . ... . . . . . ... ................... " << endl; Sleep(50);
cout << ". .... . . . . . . . . . . . . . . . .   SBs::1DGORBBBBO; .r;, ,..  .::vUppGp    . .     . . .   .   . . . . . . . ... . . ... . ... ..... ... ...... " << endl; Sleep(50);
cout << ". ... ... . . . . . . . . . . . . .     JLwMi;Z5JOEBBBp;;  ,r;r:, .,::r1EHZZM;      . . . . . . . . . .   . . . . . . ... . ... . . . ..... ..... ... " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . . . . . .   .  ,w;K6:7aBQ;rS2,.:: .:;77i;;irLJ6ppXpOHL:         . . . . . .   . . . . . . . . ... . . . . . ... ... ........ " << endl; Sleep(50);
cout << ". ... . . . . . . . . . . . . . . . .     ,rp;;rr:csr. :i:. .,, rX;rvsSSaU2XE5BBB           . . . .   .   . . . . . . . . . . . ......... ... ....... " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . . . . . . . .     :,:;:,,,.   :i:.  :LDBB;:;r7ssJ1P6KKBBBBBBs     . .   . . .     . . . . . . . . . ....... . ... ....... .. " << endl; Sleep(50);
cout << ". . . . . . . . . . . . . . .   .   . . .   :::7r:,...:r;;s7LGBBg7::;7rrsJZZEEGEBBBBBBBi        . .   . . . . . . . . . . . . ..... ... . ... . ..... " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . . . . . . . . . .   .:ivs;::;v7,LQBMBgr.:;aQBrLZMgDDROGBBBBBBBBBr           . . .   . . . . . . . . . . . . ..... . ... . .. " << endl; Sleep(50);
cout << ". . . . . . . . . . . .   . . . . .   .          i5L777;:.,..:;rBBBBBr:sRRggMROBBQBBBBBQBBBPL:              . . . . . . . . . . . . ... ... ..... ... " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . . . . . . .     . .      :a2Lrr;rr7PBgQPJs1r:rsXggROgBBBBQBBBBBBBBBBBQBMJ:          . . . . . . . . . . . . ... ............ " << endl; Sleep(50);
cout << ". . . . . . . . .   . . . .   . . .       .   .    .1Ss;rOMOp7;rspEsr;rL6ggDRBBBBBBBBQBBBBBBBBBBBBBBBDJ:            . . . . . . . . . . ..... . . . . " << endl; Sleep(50);
cout << ".  . . . . . . . .   .     . . . .     .   .         :wK2r..,r1PX7..,:LEQBRBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBOc.          . . . . . . . . . . ... ...... " << endl; Sleep(50);
cout << ". . . . . . . .         .     . .   .         .         7Gs;:::.  ,:7SQQBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBB1;       . . . . . . . . . . ... . ... " << endl; Sleep(50);
cout << ". .. .     . . . . . .   .   . . . .       . .       .rXBBBBK7::;1PgMQRBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBQBBB5    . . . . . . . . . . . ... .. " << endl; Sleep(50);
cout << ". . . . . . . . . .     .   . . .     . .         ;pBBBBBBBBBBBQBQQGOEBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBB;   . . . . . . . . . ..... ... " << endl; Sleep(50);
cout << ". .. . . . . .   .   . .   . . .     .         vQBBBBBBBBBBBBBBBBBBBMBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBQBBBBBQBBBBBBBBBB.   . . . . ... . . ... . . .. " << endl; Sleep(50);
cout << ". . . . . . . .     . .   .   . .           LBBBBBBBBQBQBBBQBBBBBBBBBQBQBQBBBBBBBBBBBBBBBBgRBBBBBBBQBBBBBQBQBQBBBBBBBBBg  . . . . . . . . ... . ..... " << endl; Sleep(50);
cout << ". .. .   . . .   . . . . . .             cMBBBBBBBBBBBBBBBQBBBBBBBQBBBQBBBQBBBBBBBBBBBQBBBpBQBQBBBBBBBBBBBBBBBBBBBBBBBBB   . . . . . . . ... ... .... " << endl; Sleep(50);
cout << ". . . . . . . . . .         .     .     BQBQBQBBBQBBBBBBBBBBQBBBBQMQBBBQBBBBBBBBBQBBBBBBBgBBBBBBBBBQBQBQBBBBBBBBBBBBBBBQ    . . . . . . . . ... . ... " << endl; Sleep(50);
cout << ". .. . . .           . .               OBBBBBBBBBBBBBBBBQBBBBBBBBBRBBBQBBBBBBBBBBBBBQBBBBEBBBBBBBBBBBBQBBBBBQBBBBBBBBBQB:  . . . . . . . . . . . .... " << endl; Sleep(50);
cout << ". . . .     . .   .       .     .     .BBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBQBBBBBQBBBBBBgBBQBBBBBBBQBQBBBBBBBBBBBBBBBBBBa   . . . . . . . . . . . ... " << endl; Sleep(50);
cout << ".  . . . . . . . . .       .     .    ;BBBBBBBBBBBBBMBBBBBBBBBQBBBBPOBBBBBQBBBQBQBBBQBBBGBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBB    . . . . . . . . . . . .. " << endl; Sleep(50);
cout << ". . . . . .           . .   .         7BBBBBBBBBBQBQQBBBBQBBBBBBBBBBRQBQBBBBBBBBBBBQBBBEBBBBBQBBBQBBBBBBBBBBBBBBBBBBBQBBB,  ... . . . . . ....... . . " << endl; Sleep(50);
cout << ".  . . .   . . . . .     . .     .    7BBBBBBBBBBBBBMBBBBBBBBBQBBBBBBBBBBBBBBBBBBBRGRBQgBBBBBBQBBBBBBBBBQBBBBBBBBBBBBBBBBB   . . . . . ... ... . .... " << endl; Sleep(50);
cout << ". .   . .   .       . . .             wBBBBQBBBQBBBBBQBBBQBBBBQBBQBBBBBBBBBBBQBBBRgcKBRBBQBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBJ   . . . . . ... . ....... " << endl; Sleep(50);
cout << ". .. . . .   .       .     .          BBBBBBQBBBBBBBBBBBBBBBBBQBQBBBMBBBQBBBBBBBBBKsBBDBBBBBQBBBQBBBBBBBQBQBQBBBBBQBBBBBBBD  . . . . . . . . . ...... " << endl; Sleep(50);
cout << ". . . . . .   .     .   .       .     BQBQBBBQBBBQBQBQBBBBBBBBBBBQBRBQBBBBBQBBBQBBBBBDBBBBBQBBBQBQBQBBBBBBBBBBBBBBBBBBBBBB:   . . . . . . . . . ..... " << endl; Sleep(50);
cout << ". .. . . .   .   . .   . .     . .   :BBBBBBBBBBBBBBBBBBQBBBQBBBQMRBQBBBBBBBBBBBBBBBQgBBBBBBQBBBBBBBBBBBBBQBQBBBBBQBBBQBBR   . . . . . . . ... . .... " << endl; Sleep(50);
cout << ". . .   . .   .     . .   .     .    ;BBBBBBBBBBBBBBBQBBBBBBBQBBQRBQBBBBBBBBBQBBBBBBRQBQBBBBBQBBBBBBBQBBBBBBBQBBBBBBBBBBBg  ... . . . . . ... . . ... " << endl; Sleep(50);
cout << ".  . . . . . .               .        BBBBBBBBBBBBBBBBBBBBQBQBBBRBBQQBBBBBBBQBBBBBQBOBBBQBBBBBBBBBBBQBQBBBBBBBBBBBBBQBBBQQ   . . . . . . . . . . . .. " << endl; Sleep(50);
cout << ". . . . . . . .     . .         . .  .BBBBBBBBBBBBBBBBBQBQBBBQQMBQBMBQBQBQBQBBBBBQBBQBBBBBBQBBBBBBBBBBBQBBBBBBBBBQBBBBBBBG  . . . . ... ....... . ... " << endl; Sleep(50);
cout << "  .. .   . . .   .     .     .       :BBBBQBBBBBBBBBBBBBBBBBBQRBBBQBQBBBBBBQMBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBX   . . ..... ..... ..... .. " << endl; Sleep(50);
cout << ". . . . . .     .           .         RBBBBBBBBBBBBBBBBBBQBBBQBBBBQBBBBBBBBMQQBQBBBgBQBBBQBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBL  . . . . . . ....... . ... " << endl; Sleep(50);
cout << ".  . . .   . . .   . . . .   . .      5BBBBBBBQBBBBBQBBBBBQBBBQBBBMBBBQBBBBQMBBBQBBgBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBr   . . . . . . . .......... " << endl; Sleep(50);
cout << ". . .   . .   . . . . .     . .       BBBBBBBBBBBBBBBBBBBBBBBQBBBMBBBBBBBBBQQQBBBQBQBBBBBQBQBBBBBBBBBQBBBBBBBBBBBBBBBQBBB,  . . . . . . . . . . . ... " << endl; Sleep(50);
cout << ". .. . . . . . . .   .         .     .BBBBBBBBBBBBBBQBBBBBBBBBBBBQBBBBBBQBBQBBQBBBQBBBBBBBBBBBBBBBBBQBBBBBQBBBQBQBBBBBBBB    . . . . . . . . . . .... " << endl; Sleep(50);
cout << ". . . . .   . . .                 .  ;BBBBBBBQBBBBBBBBBBBBBQBBBBBQBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBB   . . . . ................. " << endl; Sleep(50);
cout << "  .. . . .   . . . .     . .     .   wBBBBBBQBBBBBBBBBBBBBBBBBBBQBBBQBBBBQQBQBBBQBBBBBQBBBBBBBBBBBBBBBQBBBBBBBQBBBBBBBBBK  . . . . . . ... ... ... .. " << endl; Sleep(50);
cout << ". . . . . . . . . . . . . . . .   .   BBBBBBBQBBBQBBBBBBBQBBBBBQBQBBBBBBBBBBBQBBBBBBBQBBBBBBBBBBBBBQBBBQBBBBBBBBBBBQBBBQ:   . . . . ..... ..... . ... " << endl; Sleep(50);
cout << " .. . . . .   . . .   .   . . . .   7BBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQB   . ..... . . . . . ........ " << endl; Sleep(50);
cout << ". . . .   . .   . . . . .   . .      QBBBQBBBBBQBBBQBBBBBQBBBBBBBBBBBRQMBQQRBQBQBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBR  . ... ... . ... ... ... ... " << endl; Sleep(50);
cout << ". .. .   . . .   .   .     .   . .   RBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBB7   . . . . ..... ... . ...... " << endl; Sleep(50);
cout << ". . .   . . . .   . .   . . . . .     BBBQBQBQBBBBBBBBBQBBBBBQBBBBBQBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBB   . ... . . . ... ... ....... " << endl; Sleep(50);
cout << ".  . . . . . . .     . .       .     JBBBBBBBBBBBBBBBBBBBBBBBBBBMMRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBB  ... . . . . . . . . ... .... " << endl; Sleep(50);
cout << ". . . .   . . . . . . . . .   . .   ZQBBBBBBBBBBBBBBBBBBBBBBBQBQQBBBBQBQBQBBBBBBBQBBBBBBBQBQBBBQBBBBBBBBBBBBBBBQBQBBBBE   ..... ... . . ... ... ..... " << endl; Sleep(50);
cout << "  . . . .   . . . . . . .   . .    PBBBBBBBBBQBBBBBBBBBBBBBBBBBMBBBBBQBBBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBQBBBQBBBBBBBi  . . . . ... . . ....... . .. " << endl; Sleep(50);
cout << ". . .     . . . . .   .   . . . .    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBQBQBBBBBBBBBQBBBBBBBQBBBBBQBQBBBQBBBBBBBBBB  ..... ....... . . . ... . ... " << endl; Sleep(50);
cout << ".  . . .   . .       . .     . .   2BBBBBBBBBBBBBBBBBBBBBBQBBBBBMQRBBBQBBBBBBBBBBBQBBBBBQBQBBBBBBBBBBBBBQBBBBBBBBBQBQB   ......... ... ......... .... " << endl; Sleep(50);
cout << ". . . . . . . .   . . . . .   .    BBBBQBBBBBQBBBQBBBBBBBBBBBQBBQQBQBBBQBBBQBBBBBBBBBBBQBQBBBBBBBBBQBBBBBQBBBBBBBBBBBr  . ... . . . . ..... . ... ... " << endl; Sleep(50);
cout << ".  .   . . . .   . . . .     . .   7QBBBBBBBQBBBBBBBBBBBQBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBBBBBBBB    . ....... ....... .......... " << endl; Sleep(50);
cout << ". . . . . . .   . . . .   .   .   sQBBBQBQBBBBBBBBBBBBBOBQBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBQBBBBBQBQBBG   . . . ... . ... ..... . ..... " << endl; Sleep(50);
cout << "  .. . . . . .   .       .   . .  LBBBBBBBBBQBBBBBBBBw gBBBBBBQBQBBBQBQBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBB   ... ... . ..... . . . ........ " << endl; Sleep(50);
cout << ". ... . .   . . .     . . . . .   JBBBBBBQBBBBBBBBBBJ HBBBBBBBBQBQBBBBBBBBBBBBBBDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBH  . . . . ... ..... ... . ....... " << endl; Sleep(50);
cout << ". .. .     . . . . . . .     . .  QBBBBBBBQBBBQBBBBBr.BBBBBBBBBBQBQBQBBBQBBBQBBBEBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG   . . ..... . ..... ..... ...... " << endl; Sleep(50);
cout << ". . . . .   . .   . . . . . . .   BQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBB    ... ... ... ....... ..... ... " << endl; Sleep(50);
cout << ".  . . . . . . . . . . . . . .    BBQBBBQBBBBBBBBBBBBBBBQBBBBBBBQBQBBBBBBBBBBBQBBBBBQBBBBBBBBBBBQBBBBBBBQBBBBBBBQBBBp  ..... . ... . . . ......... .. " << endl; Sleep(50);
cout << ". . . . .   . .   .   . . . . .  ,BBBBBBBBBBBBBBBQBBBBBBBQBBBQBQBBBBBBBBBBBQQQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBi    . ........... ............. " << endl; Sleep(50);
cout << ". .. . . . .   .   . . . . .     :BBBBBBBBBBQBQBBBBBQPBBBBBBBBBBBBBBQBBBQBRQQBQBBBBBBBBBBBBBQBBBBBBBBBQBQBQBBBBBBBBBBB,  . . ........... ... . ...... " << endl; Sleep(50);
cout << ". ... . . . . . . .   .   .   .  rBBBBBBBBBBBBBQBBBBBBBBBBBBBBBQBBBQBBBBQRBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB,  . ... ... ... . ........... " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . .   .   UBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBQBQBBQBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBB  .. ..... .................. " << endl; Sleep(50);
cout << ". ... . . . . .     .     . . .  cBBBBBBBBBBBQBQBBBQBBBBBBBBBQBQBQQQBQBBBBBQBBBBBBBQBBBBBBBBBBBQBQBBBBBBBBBBBBBQBQBBBBBi  ......... ................. " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . . . .   gBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBBQBBBQB   ... ..... ....... .......... " << endl; Sleep(50);
cout << ". ... . . . . . .   . . . . . .  HBBBBBBBBBBBBBBBQBBBBBQBBBBBBBQBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB:  ...... ..................... " << endl; Sleep(50);
cout << ".  . . . . . . . . . . . . . .    BBBBBBBBBBQBBBBBBBBBBQQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBQBQBBBBBQBBBBBBBBBBBBB;  . ....... .................. " << endl; Sleep(50);
cout << ". . . . . . . . . . . . . . .    BBQBBBBBBBQBBBBBBBBBBBQBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBQBBBBBBBQBBBBBQBBBBBBBQBBBBO   . ....... ................, " << endl; Sleep(50);
cout << ".  . . . . . . . . . . . . . .  QBQBQBBBBBBBBBQBBBBBBBBBRBBBQBQBBBBBBBBBQBBBBBBBQBBBQBBBBBQBBBBBBBBBQBBBBBBBBBBBBBQBBBBBU    . ...................... " << endl; Sleep(50);
cout << ". . . . . . ... . . . . . . .   EBBBBBBBBQBBBBBQBBBBBRBBBMBBBQBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBB  ......................... " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . . . .   BBBBBBBQBBBBBQBBBBBBQRBBBBBBBBBBQJQQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBB:UBBP  ........................ " << endl; Sleep(50);
cout << ". . . . . . . . . . . . . . .    BBBBBBBBBBQBBBBBBBBBBBMQMBBBBB;:: .pRBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBQBBBB  BBB   ....................... " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . . .    gBBBBBBBBBBBBBBBQBBBBBQBBBBBQB,5csp:i5:QBBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBB  BBB  ........................ " << endl; Sleep(50);
cout << ". ... . . . . . . . . . . . .  ;BBBBBBBBBBBBBBBBBBBBBBBBBBBB7 rQp1Bv:r, OBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBBBQBQBBBBBBBBBB iBBB  ........................ " << endl; Sleep(50);
cout << ".  . ... . . . . . . . . . .   BBBQBBBQBBBBBBBBBBBQBBBBBQBr  .,2Bs,:,HB1;BBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBBB BQBB  ........................ " << endl; Sleep(50);
cout << ". ..... . . . . . . . . . .   rQBQBMQMBBBBBBBBBBBBBBBBB6i  .,.cZ2;:iGBBBBBBQBQBBBBBQBBBBBBBQBBBBBBBBBBBBBBBQBBBBBQBQBB BBQp  ......................., " << endl; Sleep(50);
cout << ". .. ..... . . . . . . . . .  QBBQQBQBBBQBQBBBBBBBBBBH,  ,,,,,:ssURBQBBBBBBBBBQBQBBBBBBBBBBBQBBBBBBBQBBBBBBBBBBBBBQBBK,BQB:  ........................ " << endl; Sleep(50);
cout << ". . . ... . . . . . . . . .  .BBBRQBBBBBEs1PBBBBBBBp, .,:::,:::...,:rSBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBQBBBBBBBQBBBLHBBB  ........................, " << endl; Sleep(50);
cout << ". .. . . . . . . . . . . .   :BBQBBBBw.    ...7BBBr  :,:,:::::,:,.   SBBBBBBBBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBQBBBBBBBQ7BBBB  ......................... " << endl; Sleep(50);
cout << ". . . . . . . . . . . .     :BBBBBBQ: ,.,,:;::.;BG ,;:,,:,;:;:::,  ;BQBQBQBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBQBBBBBBBBBrBBBL  ......................... " << endl; Sleep(50);
cout << ". .. . . . . . . . . .     BBBBBBBBL.::;:::;;r;:v:,r;::::;;:,:::.:aBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQSBBB. .......................... " << endl; Sleep(50);
cout << ". . . . . . . . . .      LBBBQBQBBBr::;::,::rLr;,.:6r;Jsci:.:;:,7BBBBBBQBBBBBQBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBB  ........................., " << endl; Sleep(50);
cout << ". .. . . . . .   .     .BBQBQBBBBBQr:;::,:::UQ::::wS,;Xw;7rcL7;sQBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBp  .......................... " << endl; Sleep(50);
cout << ". ... . . . . . .     sBBBBBBQBQBBBr;::,:,:JgQ7.:Lg::7G::rM5;rwBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBB; .........................., " << endl; Sleep(50);
cout << ". .. . . . . . .     BBBBBBBBBQBBBB7::::::rBBBB;sgr:rEJ.:JB::rZBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBQBQBBBQB  ........................... " << endl; Sleep(50);
cout << ". . . . . . . .    :BBBBBBBBBBBBBBB:.rr:;:cpBBBSL6:,wE::cM5 r1BBBBBQBBBBBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBBBBBBBBB  .........................., " << endl; Sleep(50);
cout << ". .. . . . . .    XBBBQBBBQBBBBBBBBs,iLs;::;BBBBSOMgpJ.;2BZ,rgBBBBBBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBw ............................ " << endl; Sleep(50);
cout << ". ... . . ...    BBBBQBBBBBBBBBQBQBBa::r7:,.7QBBB7gQBBBBBMBBBQBBBBBQBQBBBBBBBBBBBBBBBBBQBBBBBBBQBBBBBBBBBBBBBQBBBQBBBBB, .........................,., " << endl; Sleep(50);
cout << ". .... . ...   7QBBBBBBBBBBBBBBBQBBBBr:,:s:, XBBQg: LBHBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBGLBBBBB; BBBB  ........................,... " << endl; Sleep(50);
cout << ". ..... . .   gBBBBBBBBBBBBBBBBBBBBBBBr7r7r:,;JGBBBQr    vBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBD:;:      7H:   BBQZ ....................,.....,., " << endl; Sleep(50);
cout << ". .. . .    ,BBBBBBBBBBBQBBBBBBBBBQBBBDr;.:25L;:vQQi      BBBBQBBBBBBBBBBBBBQBBBBBBBBBBBBBQBBBBBBB;               sBBB: .............,...,.....,...,, " << endl; Sleep(50);
cout << ". ... .    2BBBBBBBBBBBBBQBQBBBBBBBBBBBQr:;1gEXwJisL.    sBQBBBBBQBBBQBBBBBBBBBQBQBBBBBBBBBBBBBB5   . ..........  BBBB  ..............,.,.,.,.,.,.,,, " << endl; Sleep(50);
cout << ". .. .   ,QBBBBBBBBBBBBBBBQBBBBBBBBBBBBBQBQKswagBBZMB  HBBBBQBBBBBQBBBQBBBBBBBQBBBBBBBBBQBQBBBS    ....... .....  QBBQ  .....,.....,.,.,.,.,.,.,.,.,,." << endl; Sleep(50);
cout << ". . .   XBBBBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBB::Jr  PQBQBBBBBBBBBBBBBBBBBBBBBQBQBQBBBBBBBBBK    ........... .  7BBBr  ....,.............,.,.,.,.,,, " << endl; Sleep(50);
cout << ". .   .BBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBBBQ,      BBBBBBBBQBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBQL   ............  BBBB  ......,.,.,.,.....,.,.,.,.,.,, " << endl; Sleep(50);
cout << ".    rBQBBBBBBBQBBBBBQBBBBBBBBBBBBBBBBBBBBBBBg    .  .BBBBBBBBBBBBBBBBBQBBBBBBBBBQBBBBBBBB;.BBBQQ   ...........  BBBB  .....,.,.,.,.,.,,,.,,,.,,,,,,, " << endl; Sleep(50);
cout << ".   EBBBBBBBBBBBBBBBBBQBBBBBBBQBBBBBBBBBQBQB;    ...  QBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBp   aBBBR   .......... iBBBL  ..,.,.,.,.,.,.,.,,,.,,,,,,,.,,." << endl; Sleep(50);
cout << "  :BBQBQBBBBBBBBBBBQBBBBBBBBBBBQBBBBBBBBBBa   ......  6BBBBBBBBBBBBQBBBBBQBBBBBBBQBBBBBBBBB   5BBB; ..........  BBBB. ....,.,.,.,.,,,,,,,,,.,.,,,,,,:." << endl; Sleep(50);
cout << " 1BBBBBBBBBBBBBBQBQBQBBBBBQBQBQBBBBBQBBBZ    .......  :BBB,,QBQBQBBBBBBBBBBBBBBBQBQBBBQBBBBB   BBBB  .........  QBBB  .,.,.,.,.,,,,,,,.,,,,,,,,,,:,:,." << endl; Sleep(50);
cout << "BBBBBQBQBQBBBBBBBBBBBBBBBBBBBBBQBBBBBQB    ..........  BBBE pQBBBBBBBBBBBBBQBBBBBBBBBBBQBBBBB  gBBB. ........  ;BQBU .,.,.,.,.,,,,,,,,,,,,,,,,,,,,:,:." << endl; Sleep(50);
cout << "BBBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBBBB:    ..........   DBBQ  LBBBBBBBBBBBBBBQBBBBBBBBBQBBBBBBL rBBBw ......... gBBB: ..,.,,,,,,,.,,,,,,,,:,:,,,,,,,::." << endl; Sleep(50);
cout << "BBBQBBBBBQBBBQBBBBBBBBBBBBBBBBBBBBE.    . ..... .....  :BBB: XBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBQ  BQBB  .......  BBBB  .,.,.,,,,,,,,,,,,,,:,,,:,:,:,:,:." << endl; Sleep(50);
cout << "BBBBBBQBQBBBQBBBBBBBBBBBBBQBBBBBR     ................  BBBP BBBBBBBBBBBBBQBQBBBBBBBBBBBBBBBBB  BBBB. .....,. :BBBp .,.,,,.,,,,:,,,,,,,,,,,,,:,:,:,::." << endl; Sleep(50);
cout << "BQBBBQBBBBBBBBBBBBBBBBBQBBBQBBB,    ..................  OBBBcBBBDBBBBQBBBQBBBBBQBBBQBBBBBBBBBB, SBBBs ....,.. 6BBB; ,,,,,,,,:,:,:,:,:,:,,,:,:,:::::::." << endl; Sleep(50);
cout << "BBQBBBBBBBBBBBBBBBBBBBBBQBBBS.   .....................  ;BBBQDBB ;BBBBBBBBBBQBBBBBBBBBBBBBBBQB: ,BBBM  ,.,..  QBBB  .,,,,:,,,:,,,:,:,:,:,:,:,:,::::::." << endl; Sleep(50);
cout << "BBBBBBBBBBBBBQBBBBBQBQBBBB7    ...,....................  QBBPGB7   PBBBBBBBBBBBBBBBQBBBBBBBBBB,  QBBB  .,,,. :BQBR .:,:,:,:,:,:,:,:,:,:,:,:,:,:,:::,:." << endl; Sleep(50);
cout << "BBBBQBBBBBBBBBBBBBBBBBBBBB  .....,...........,.......... GQBBBB  .  .BBBBBQBQBQBBBQBBBBBBBBBBB   MBBB7 ,,,,, PBBB7 ,::,:,:,::::::::::::::::::::::::::," << endl; Sleep(50);
cout << "BQBBBBBBBQBBBBBBBBBQBBB                                  .BBBBp        sBBBBBBBBBQBBBBBBBBBBBJ   :BBBD  . .  BBBB   ......................,...,.,.,,:." << endl; Sleep(50);
}
int main() {
    nhapten();
    giadinh();
    cout << "dang xu ly: 10% ..." << endl; 
    Sleep(1000);
    cout << "dang xu ly: 20% ..." << endl; Sleep(1000);
    cout << "dang xu ly: 30% ..." << endl; Sleep(1000);
    cout << "dang xu ly: 40% ..." << endl; Sleep(1000);
    cout << "dang xu ly: 50% ..." << endl; Sleep(1000);
    cout << "dang xu ly: 60% ..." << endl; Sleep(1000);
    cout << "dang xu ly: 70% ..." << endl; Sleep(1000);
    cout << "dang xu ly: 80% ..." << endl; Sleep(1000);
    cout << "dang xu ly: 90% ..." << endl; Sleep(1000);
    cout << "dang xu ly: 100% ..." << endl; Sleep(1000);
    cout << "xu ly hoan tat!";
    velogo(); 
    vetoctruong();
    cout << "Cong "; Sleep(100);
    cout << "Loi "; Sleep(100);
    cout << "From "; Sleep(100);
    cout << "Mixi "; Sleep(100);
    cout << "Gaming "; Sleep(100);
    cout << "With "; Sleep(100);
    cout << "Love"; Sleep(100);
}
  
